#maven仓库包装器，配置好版本和链接，就不用下载maven就可以使用
# maven仓库就是存放所有依赖包（jar）的地方
wrapperVersion=3.3.4
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.16/apache-maven-3.9.16-bin.zip
